# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/debian-base:6.1.3"
  amd64: "ghcr.io/hassio-addons/debian-base:6.1.3"
  armhf: "ghcr.io/hassio-addons/debian-base:6.1.3"
  armv7: "ghcr.io/hassio-addons/debian-base:6.1.3"
  i386: "ghcr.io/hassio-addons/debian-base:6.1.3"
labels:
  org.opencontainers.image.title: "Whatsapp Add-on"
  org.opencontainers.image.description: "Whatsapp integration for Home Assistant."
  org.opencontainers.image.source: "https://github.com/gajosu/whatsapp-ha-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2022.09.1"
